version: "3"
services:
  backend:
    image: invincibot/hackmit-2022-backend
    ports:
      - "5000:5000"
  frontend:
    image: invincibot/hackmit-2022-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  nginx:
    image: invincibot/hackmit-2022-nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - frontend
